# Generated by Django 3.0.3 on 2020-02-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('licensePlate', 'licensePlateState', 'vin'), name='Unique vehicle'),
        ),
    ]
