# Generated by Django 3.0.3 on 2020-02-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_auto_20200207_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatecheck',
            name='checkID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
